# Generated by Django 4.0 on 2022-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
