# Generated by Django 4.0 on 2022-10-02 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_drivers_driver_lat_drivers_driver_long_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Request', 'Request'), ('Accept', 'Accept'), ('Delivering', 'Delivering'), ('completed', 'Completed')], default='Request', max_length=20)),
                ('carier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_lat', models.CharField(max_length=15)),
                ('delivery_long', models.CharField(max_length=10)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField(default=0)),
                ('pickup_long', models.FloatField(default=0)),
                ('resturant_name', models.CharField(blank=True, max_length=900, null=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'active'), ('Delivered', 'Delivered'), ('cancelled', 'cancel'), ('completed', 'Completed'), ('pending', 'pending')], default='creating', max_length=20)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('distance', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('carier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='job',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='jobrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobrequest'),
        ),
    ]
