# Generated by Django 4.0 on 2022-11-07 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_drivers_online_alter_jobrequest_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='totaldelivery',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('carier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverrating', to='api.drivers')),
                ('jobrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrating', to='api.jobrequest')),
            ],
        ),
    ]
