# Generated by Django 4.0 on 2022-09-26 01:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ownerprofiles_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='driver_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_long',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_lat', models.CharField(max_length=15)),
                ('delivery_long', models.CharField(max_length=10)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField(default=0)),
                ('pickup_long', models.FloatField(default=0)),
                ('photo', models.ImageField(upload_to='job/photo/')),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('processing', 'Processing'), ('delivering', 'Delivering'), ('cancelled', 'cancel'), ('completed', 'Completed'), ('picking', 'picking')], default='creating', max_length=20)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('distance', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('carier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ownerprofiles')),
            ],
        ),
    ]
