# Generated by Django 4.0 on 2022-10-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driverrequest_jobrequest_user_owner_delete_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='name',
        ),
    ]
