# Generated by Django 4.0 on 2022-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_driverrequest_jobrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='delivery_lat',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='delivery_long',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
